### ISSUE TITLE
Tiles entity per chunk

### ISSUE THREAD

**Issue by Heriptik** [Barteks2x/ChunkGenLimiter#1]
Hello, can you add the tile limit per chunk (16x16x256) in your mod ?

Because I have a server with more than 100 players and put 350-400 tiles per chunk

I would like to reduce to 200 tiles/chunk max

**Comment by Niko-sk2x** [comment]
This is beyond the scope of this mod. 

Limiting tile entities is also not feasible without breaking mods, potentially even causing crashes. And even if it doesn't crash, it could lead to people losing their items in certain cases.

And even then that's far more significant change than just limiting chunk generation speed. MC already had the code to limit chunk generation speed, it was just set to absurd numbers that are not going to ever be reached on real hardware. MC has nothing to limit amount of tile entities. It would have to be written from the scratch. And it would definitely conflict with SpongeForge.
